# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24dda6875322d1f7d642672d0f40e10936a9a2c734c36d0dbf23f1870a25ab5e1ef95a81411f9b1a071349fe482dda5fefcdbdccde0f0bb9ab7bfa25f2698f34

test:
  secret_key_base: 42371fa50c448478ff9217aba10f7475f1ab22d636ea1b85b7037b6c76d0173cf9fb09ae3e0eb766d08dff76d833af88c716cdf92fa489f35d9360353b18d679

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
